# Schema for the farmOS entity third party settings.
log.type.*.third_party.farm_entity:
  type: mapping
  label: 'farmOS entity settings'
  mapping:
    default_quantity_type:
      type: string
      label: 'Default quantity type'
